/* Generated By:JavaCC: Do not edit this line. MyGrammarTreeConstants.java Version 5.0 */
package javacc;

public interface MyGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTSTARTTYPE = 2;
  public int JJTFUNTYPE = 3;
  public int JJTFUNCTIONSTATEMENT = 4;
  public int JJTPARAMETERSTATEMENT = 5;
  public int JJTFUNCTION = 6;
  public int JJTPARAMETER = 7;
  public int JJTSTATEMENT = 8;
  public int JJTSTATEMENTBLOCK = 9;
  public int JJTSEQUENCESTATESTATEMENT = 10;
  public int JJTSTATESTATEMENT = 11;
  public int JJTSTATESTATEMENTBLOK = 12;
  public int JJTTYPE = 13;
  public int JJTCALSTATEMENT = 14;
  public int JJTSWITCHSTATEMENT = 15;
  public int JJTCASESTATEMENT = 16;
  public int JJTASSIGNSTATEMENT = 17;
  public int JJTASSIGNROP = 18;
  public int JJTFORSTATEMENT = 19;
  public int JJTIFSTATEMENT = 20;
  public int JJTCONDITION = 21;
  public int JJTORBOOLEXPRESSION = 22;
  public int JJTANDBOOLEANEXPRESSION = 23;
  public int JJTNOBOOLEANEXPRESSION = 24;
  public int JJTBOOLEXPRESSION = 25;
  public int JJTWHILESTATEMENT = 26;
  public int JJTWHILESTATEMENT1 = 27;
  public int JJTWHILESTATEMENT2 = 28;
  public int JJTEXPRESSION = 29;
  public int JJTADDITIVEEXPRESSION = 30;
  public int JJTMULTIPLICATIVEEXPRESSION = 31;
  public int JJTUNARYEXPRESSION = 32;
  public int JJTIDENTIFIER = 33;
  public int JJTINTEGER = 34;


  public String[] jjtNodeName = {
    "Start",
    "program",
    "StartType",
    "FunType",
    "functionstatement",
    "parameterstatement",
    "function",
    "parameter",
    "statement",
    "statementBlock",
    "SequencestateStatement",
    "stateStatement",
    "stateStatementBlok",
    "type",
    "calStatement",
    "SwitchStatement",
    "CaseStatement",
    "assignStatement",
    "AssignRop",
    "ForStatement",
    "ifStatement",
    "condition",
    "OrBoolExpression",
    "AndBooleanExpression",
    "NoBooleanExpression",
    "BoolExpression",
    "whileStatement",
    "WhileStatement1",
    "WhileStatement2",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=85fb6c2380581db09047493471611ec3 (do not edit this line) */
